server:
  host: "0.0.0.0"
  port: 8000
  output_path: "/tmp"

ollama:
  host: "localhost"
  port: 11434
  timeout: 600
  default_model: "hf.co/RefalMachine/RuadaptQwen2.5-32B-Pro-Beta-GGUF:Q8_0"

openapi:
  title: "AI Gateway"
  version: "1.0.0"
  summary: "Сервер управления LLM моделями Ollama и Hugging Face"
  description: |
    Сервер запущен с конфигурацией по умолчанию. Для промышленной эксплуатации запустите сервер с корректно настроенными параметрами хоста
  contact:
    name: "Nikolay Sedov"
    url: "https://nicksedov.github.io/"
  license_info:
    name: "ТОЛЬКО ДЛЯ ЛИЧНОГО ИСПОЛЬЗОВАНИЯ"
  security_schemes:
    Bearer:
      type: "http"
      scheme: "bearer"
      bearerFormat: "UUID"
      description: "Требуемый формат: UUID"
  security:
    - Bearer: []

logging:
  file_path: "/var/log/ai-server_default.log"
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"