server:
  host: "0.0.0.0"
  port: 7999
  storage_root: "/app/storage"
  api_key: cbebbe70-0ba4-494f-8c85-41da575228d9

ollama:
  host: "host.docker.internal"
  port: 11434
  timeout: 300  # seconds
  default_model: "qwq:32b-q8_0"

openapi:
  title: "LLM Server API"
  version: "1.0.0"
  summary: "Private LLM model management server"
  description: |
    # Key Information:
    - Used exclusively for owner's personal purposes
    - Testing and deployment of Language Learning Models (LLMs)
    - Not intended for public use
    - Access strictly limited to authorized users
    # Technical Details:
    - Integrated with Ollama for model operations
    - Huggingface-hosted models support
    - OpenAI API format compatible
  contact:
    name: "Nikolay Sedov"
    url: "https://nicksedov.github.io/"
  license_info:
    name: "PRIVATE USE ONLY"
  security_schemes:
    Bearer:
      type: "http"
      scheme: "bearer"
      bearerFormat: "UUID"
      description: "Required format: Bearer <your-secret-key>"
  security:
    - Bearer: []
