server:
  host: "0.0.0.0"
  port: 8000
  output_path: "/tmp"

ollama:
  host: "localhost"
  port: 11434
  timeout: 300
  default_model: "llama2"

openapi:
  title: "API сервера LLM"
  version: "1.0.0"
  summary: "Приватный сервер управления моделями LLM"
  description: |
    Сервер запущен с конфигурацией по умолчанию. Для промышленной эксплуатации запустите сервер с корректно настроенными параметрами хоста
  contact:
    name: "Nikolay Sedov"
    url: "https://nicksedov.github.io/"
  license_info:
    name: "ТОЛЬКО ДЛЯ ЛИЧНОГО ИСПОЛЬЗОВАНИЯ"
  security_schemes:
    Bearer:
      type: "http"
      scheme: "bearer"
      bearerFormat: "UUID"
      description: "Требуемый формат: Bearer <ваш-секретный-ключ>"
  security:
    - Bearer: []