server:
  host: "0.0.0.0"
  port: 8000
  storage_root: "/tmp"

ollama:
  host: "localhost"
  port: 11434
  timeout: 300
  default_model: "llama2"

openapi:
  title: "LLM Server API"
  version: "1.0.0"
  summary: "Private LLM model management server"
  description: |
    The server started with the default configuration. For productive operation, start the server with correctly configured host settings
  contact:
    name: "Nikolay Sedov"
    url: "https://nicksedov.github.io/"
  license_info:
    name: "PRIVATE USE ONLY"
  security_schemes:
    Bearer:
      type: "http"
      scheme: "bearer"
      bearerFormat: "UUID"
      description: "Required format: Bearer <your-secret-key>"
  security:
    - Bearer: []