server:
  host: "0.0.0.0"
  port: 8000
  output_path: "/tmp"

ollama:
  host: "localhost"
  port: 11434
  timeout: 600

openapi:
  title: "AI Gateway"
  version: "1.0.0"
  summary: "Сервер управления LLM моделями Ollama и Hugging Face"
  description: |
    Сервер запущен с конфигурацией по умолчанию. Для промышленной эксплуатации запустите сервер с корректно настроенными параметрами хоста
  contact:
    name: "Nikolay Sedov"
    url: "https://nicksedov.github.io/"
  license_info:
    name: "ТОЛЬКО ДЛЯ ЛИЧНОГО ИСПОЛЬЗОВАНИЯ"
  security_schemes:
    Bearer:
      type: "http"
      scheme: "bearer"
      bearerFormat: "UUID"
      description: "Требуемый формат: UUID"
  security:
    - Bearer: []

chat:
  image_generation:
    default_model: "black-forest-labs/FLUX.1-dev"
    default_size: "512x512"
    default_steps: 25
    default_guidance_scale: 4.5
    default_language: "auto"

  image_prompt:
    default_model: "hf.co/RefalMachine/RuadaptQwen2.5-32B-Pro-Beta-GGUF:Q8_0"
    temperature: 0.7
    top_p: 0.9
    max_tokens: 300
    system_message: "Сейчас ты помогаешь создавать промпты для генерации изображений."

logging:
  file_path: "/var/log/ai-server_default.log"
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"